; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; https://docs.platformio.org/page/projectconf.html

[env:esp32-c3-devkitm-1]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino

monitor_speed = 115200
upload_speed = 921600
upload_protocol = esptool
upload_port = /dev/cu.usbmodem1101

lib_deps =
    adafruit/Adafruit ADS1X15 @ ^2.4
    knolleary/PubSubClient @ ^2.8
    ottowinter/ESPAsyncWebServer-esphome @ ^3.1
    bblanchon/ArduinoJson @ ^7.0

build_flags =
    -DFIRMWARE_VERSION=\"1.0.15\"
    -DCORE_DEBUG_LEVEL=0
    -DOTA_PASSWORD=\"admin\"

lib_ldf_mode = deep

board_build.flash_mode = dio
board_build.f_cpu = 160000000L
board_build.filesystem = littlefs
board_build.partitions = partitions.csv
